---
image: golang:1.20-bookworm
stages:
  - build

variables:
  DEBIAN_FRONTEND: noninteractive

test_building:
  stage: build
  before_script:
    - apt-get -qq -y update
    - apt-get -qq -y install build-essential devscripts debhelper quilt wget
  script:
    - make reaction ip46tables nft46
