---
patterns:
  num:
    regex: '[0-9]+'

streams:
  tailDown:
    cmd: [ "sh", "-c", "sleep 6; echo found 1; echo found 2; sleep 10" ]
    filters:
      findIP:
        regex:
          - '^found <num>$'
        retry: 2
        retry-period: 2m
        actions:
          damn:
            cmd: [ "echo", "<num>" ]
          undamn:
            cmd: [ "echo", "undamn", "<num>" ]
            after: 1m
            onexit: true
